import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 bg-gray-100 shadow">
          <h1 className="text-xl font-bold text-black">Yehor Fal</h1>
        </header>
        <main className="p-4">
          {children}
        </main>
        <footer className="p-4 bg-gray-100 mt-8 text-sm text-center text-gray-600">
          Yehor Fal
        </footer>
      </body>
    </html>
  );
}
